import Head from "next/head";
import Header from "~/components/Header";
import HomeHero from "~/components/homeComponents/HomeHero";
import AboutUs from "~/components/homeComponents/AboutUs";
import MeetTheTeam from "~/components/homeComponents/MeetTheTeam";
import ContactUs from "~/components/Contact";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center">
        <HomeHero />
        <AboutUs />
        <MeetTheTeam />
        {/* <Projects /> */}
        <ContactUs />
      </main>
    </>
  );
}

//function AuthShowcase() {
//  const { data: sessionData } = useSession();
//
//  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//    undefined, // no input
//    { enabled: sessionData?.user !== undefined }
//  );
//
//  return (
//    <div className="flex flex-col items-center justify-center gap-4">
//      <p className="text-center text-2xl text-white">
//        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//        {secretMessage && <span> - {secretMessage}</span>}
//      </p>
//      <button
//        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//        onClick={sessionData ? () => void signOut() : () => void signIn()}
//      >
//        {sessionData ? "Sign out" : "Sign in"}
//      </button>
//    </div>
//  );
//}
//